[project]
name = "crewai-learning"
version = "0.1.0"
readme = "README.md"
# Start of Selection
# Start of Selection
requires-python = ">=3.10, <3.13"
# End of Selection
dependencies = ["crewai-tools>=0.17.0", "crewai>=0.86.0", "ipykernel>=6.29.5"]
